In [27]:
import json 
import pandas as pd 
from pandas.io.json import json_normalize #package for flattening json in pandas df

#load json object
with open('D:/Covid.json') as f:
    d = json.load(f)

#lets put the data into a pandas df
#clicking on raw_nyc_phil.json under "Input Files"
#tells us parent node is 'programs'
nycphil = json_normalize(d['features'])
nycphil.head(20)

<ipython-input-27-1134f86503b6>:12: FutureWarning: pandas.io.json.json_normalize is deprecated, use pandas.json_normalize instead
  nycphil = json_normalize(d['features'])

,attributes.OBJECTID,attributes.Province_State,attributes.Country_Region,attributes.Last_Update,attributes.Lat,attributes.Long_,attributes.Confirmed,attributes.Recovered,attributes.Deaths,attributes.Active
0,712,Grand Princess,US,1596508076000,37.648940,-122.665479,103,0,3,0
1,745,Northern Mariana Islands,US,1630300864000,15.097900,145.673900,183,0,2,0
2,727,Virgin Islands,US,1630300864000,18.335800,-64.896300,5774,0,53,0
3,741,Guam,US,1630300864000,13.444300,144.793700,10239,0,145,0
4,760,Vermont,US,1630300864000,44.045876,-72.710686,27972,0,275,0
5,769,District of Columbia,US,1630300864000,38.897438,-77.026817,54556,0,1159,0
6,762,Hawaii,US,1630300864000,21.094318,-157.498337,62229,0,589,0
7,749,Wyoming,US,1630300864000,42.755966,-107.302490,73467,0,835,0
8,770,Maine,US,1630300864000,44.693947,-69.381927,75381,0,930,0
9,734,Alaska,US,1630300864000,61.370716,-152.404419,86753,0,438,0
10,757,New Hampshire,US,1630300864000,43.452492,-71.563896,106525,0,1415,0
11,731,North Dakota,US,1630300864000,47.528912,-99.784012,116838,0,1592,0
12,714,Delaware,US,1630300864000,39.318523,-75.507141,119226,0,1877,0
13,756,Montana,US,1630300864000,46.921925,-110.454353,125616,0,1783,0
14,738,South Dakota,US,1630300864000,44.299782,-99.438828,130776,0,2064,0
15,764,Rhode Island,US,1630300864000,41.680893,-71.511780,161701,0,2764,0
16,729,Puerto Rico,US,1630300864000,18.220800,-66.590100,170217,0,2832,0
17,733,West Virginia,US,1630300864000,38.491226,-80.954453,187519,0,3064,0
18,748,Idaho,US,1630300864000,44.240459,-114.478828,217887,0,2327,0
19,718,New Mexico,US,1630300864000,34.840515,-106.248482,229509,0,4505,0

In [28]:
nycphil.to_csv('D:/umairsbfinal.csv')